plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '1.0.11'
}

version = '1.2.0'
group = 'com.macat.waystonemap'

base {
    archivesName = 'Fast_Travel_Waypoints-NeoForge-1.21.1'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
    withSourcesJar()
}

neoForge {
    version = '21.1.8'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

jar {
    archiveFileName = "Fast_Travel_Waypoints-NeoForge-1.21.1-v${project.version}.jar"
    manifest {
        attributes([
            "Specification-Title"     : "Fast_Travel_Waypoints",
            "Specification-Vendor"    : "macat",
            "Specification-Version"   : "1",
            "Implementation-Title"    : project.name,
            "Implementation-Version"  : project.version,
            "Implementation-Vendor"   : "macat",
            "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}
